package Modelo;
// Generated 18-abr-2018 14:18:14 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Administradores generated by hbm2java
 */
@Entity
@Table(name = "administradores", catalog = "bbdd_g2")
public class Administradores implements java.io.Serializable {

	private int dniAdministradores;
	private String nombreAdministradores;
	private String passwordAdministradores;
	private Date timeStamp;

	public Administradores() {
	}

	public Administradores(int dniAdministradores, String nombreAdministradores, String passwordAdministradores) {
		this.dniAdministradores = dniAdministradores;
		this.nombreAdministradores = nombreAdministradores;
		this.passwordAdministradores = passwordAdministradores;
	}

	@Id
	@Column(name = "DNI_administradores", unique = true, nullable = false)
	public int getDniAdministradores() {
		return this.dniAdministradores;
	}

	public void setDniAdministradores(int dniAdministradores) {
		this.dniAdministradores = dniAdministradores;
	}

	@Column(name = "nombre_administradores", nullable = false, length = 45)
	public String getNombreAdministradores() {
		return this.nombreAdministradores;
	}

	public void setNombreAdministradores(String nombreAdministradores) {
		this.nombreAdministradores = nombreAdministradores;
	}

	@Column(name = "password_administradores", nullable = false, length = 45)
	public String getPasswordAdministradores() {
		return this.passwordAdministradores;
	}

	public void setPasswordAdministradores(String passwordAdministradores) {
		this.passwordAdministradores = passwordAdministradores;
	}

	@Version@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "version", nullable = false)
	public Date getFecha() {
		return this.timeStamp;
	}

	public void setFecha(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

}
