package Modelo;
// Generated 18-abr-2018 14:18:14 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Carrera generated by hbm2java
 */
@Entity
@Table(name = "carrera", catalog = "bbdd_g2")
public class Carrera implements java.io.Serializable {

	private Integer idcarreraCarrera;
	private Jueces jueces;
	private String nombreCarrera;
	private String distanciaCarrera;
	private String altitudCarrera;
	private Date timestampCarrera;
	private Set<Participantes> participanteses = new HashSet<Participantes>(0);

	public Carrera() {
		
	}
	
	public Carrera(String nombreCarrera, String distanciaCarrera, String altitudCarrera) {
		this.nombreCarrera = nombreCarrera;
		this.distanciaCarrera = distanciaCarrera;
		this.altitudCarrera = altitudCarrera;
	}

	public Carrera(Jueces jueces, String nombreCarrera, String distanciaCarrera, String altitudCarrera) {
		this.jueces = jueces;
		this.nombreCarrera = nombreCarrera;
		this.distanciaCarrera = distanciaCarrera;
		this.altitudCarrera = altitudCarrera;

	}


	public Carrera(Jueces jueces, String nombreCarrera, String distanciaCarrera, String altitudCarrera, Set<Participantes> participanteses) {

		this.jueces = jueces;
		this.nombreCarrera = nombreCarrera;
		this.distanciaCarrera = distanciaCarrera;
		this.altitudCarrera = altitudCarrera;
		this.participanteses = participanteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcarrera_carrera", unique = true, nullable = false)
	public Integer getIdcarreraCarrera() {
		return this.idcarreraCarrera;
	}

	public void setIdcarreraCarrera(Integer idcarreraCarrera) {
		this.idcarreraCarrera = idcarreraCarrera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DNI_jueces")
	public Jueces getJueces() {
		return this.jueces;
	}

	public void setJueces(Jueces jueces) {
		this.jueces = jueces;
	}

	@Column(name = "nombre_carrera", nullable = false, length = 45)
	public String getNombreCarrera() {
		return this.nombreCarrera;
	}

	public void setNombreCarrera(String nombreCarrera) {
		this.nombreCarrera = nombreCarrera;
	}

	@Column(name = "distancia_carrera", nullable = false, length = 11)
	public String getDistanciaCarrera() {
		return this.distanciaCarrera;
	}

	public void setDistanciaCarrera(String distanciaCarrera) {
		this.distanciaCarrera = distanciaCarrera;
	}

	@Column(name = "altitud_carrera", nullable = false, length = 11)
	public String getAltitudCarrera() {
		return this.altitudCarrera;
	}

	public void setAltitudCarrera(String altitudCarrera) {
		this.altitudCarrera = altitudCarrera;
	}

	@Version@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "version", nullable = false)
	public Date getTimestampCarrera() {
		return this.timestampCarrera;
	}
				
	public void setTimestampCarrera(Date timestampCarrera) {
		this.timestampCarrera = timestampCarrera;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carrera")
	public Set<Participantes> getParticipanteses() {
		return this.participanteses;
	}

	public void setParticipanteses(Set<Participantes> participanteses) {
		this.participanteses = participanteses;
	}

}
