package Modelo;
// Generated 18-abr-2018 14:18:14 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Jueces generated by hbm2java
 */
@Entity
@Table(name = "jueces", catalog = "bbdd_g2")
public class Jueces implements java.io.Serializable {

	private int dniJueces;
	private String nombreJueces;
	private String apellidosJueces;
	private String telefonoJueces;
	private int idcarreraJueces;
	private Date timestampJueces;
	private Set<Carrera> carreras = new HashSet<Carrera>(0); //?

	public Jueces() {
	}

	public Jueces(int dniJueces, String nombreJueces, String apellidosJueces, String telefonoJueces) {
		this.dniJueces = dniJueces;
		this.nombreJueces = nombreJueces;
		this.apellidosJueces = apellidosJueces;
		this.telefonoJueces = telefonoJueces;
	}

	public Jueces(int dniJueces, String nombreJueces, String apellidosJueces, String telefonoJueces,
			int idcarreraJueces, Set<Carrera> carreras) {
		this.dniJueces = dniJueces;
		this.nombreJueces = nombreJueces;
		this.apellidosJueces = apellidosJueces;
		this.telefonoJueces = telefonoJueces;
		this.idcarreraJueces = idcarreraJueces;
		this.carreras = carreras;
	}

	@Id

	@Column(name = "DNI_jueces", unique = true, nullable = false)
	public int getDniJueces() {
		return this.dniJueces;
	}

	public void setDniJueces(int dniJueces) {
		this.dniJueces = dniJueces;
	}

	@Column(name = "nombre_jueces", nullable = false, length = 45)
	public String getNombreJueces() {
		return this.nombreJueces;
	}

	public void setNombreJueces(String nombreJueces) {
		this.nombreJueces = nombreJueces;
	}

	@Column(name = "apellidos_jueces", nullable = false, length = 70)
	public String getApellidosJueces() {
		return this.apellidosJueces;
	}

	public void setApellidosJueces(String apellidosJueces) {
		this.apellidosJueces = apellidosJueces;
	}

	@Column(name = "telefono_jueces", nullable = false, length = 15)
	public String getTelefonoJueces() {
		return this.telefonoJueces;
	}

	public void setTelefonoJueces(String telefonoJueces) {
		this.telefonoJueces = telefonoJueces;
	}

	@Column(name = "idcarrera_jueces", nullable = false)
	public int getIdcarreraJueces() {
		return this.idcarreraJueces;
	}

	public void setIdcarreraJueces(int idcarreraJueces) {
		this.idcarreraJueces = idcarreraJueces;
	}

	@Version@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "version", nullable = false)
	public Date getTimestampJueces() {
		return this.timestampJueces;
	}

	public void setTimestampJueces(Date timestampJueces) {
		this.timestampJueces = timestampJueces;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jueces")
	public Set<Carrera> getCarreras() {
		return this.carreras;
	}

	public void setCarreras(Set<Carrera> carreras) {
		this.carreras = carreras;
	}

}
