package Modelo;
// Generated 18-abr-2018 14:18:14 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParticipantesId generated by hbm2java
 */
@Embeddable
public class ParticipantesId implements java.io.Serializable {

	private int dniUsuarios;
	private int idcarreraCarrera;
	private int dorsalParticipantes;
	private Integer tiempoParticipantes;
	private Date timestampParticipantes;

	public ParticipantesId() {
	}

	public ParticipantesId(int dniUsuarios, int idcarreraCarrera, int dorsalParticipantes) {
		this.dniUsuarios = dniUsuarios;
		this.idcarreraCarrera = idcarreraCarrera;
		this.dorsalParticipantes = dorsalParticipantes;
	}

	public ParticipantesId(int dniUsuarios, int idcarreraCarrera, int dorsalParticipantes, Integer tiempoParticipantes) {
		this.dniUsuarios = dniUsuarios;
		this.idcarreraCarrera = idcarreraCarrera;
		this.dorsalParticipantes = dorsalParticipantes;
		this.tiempoParticipantes = tiempoParticipantes;
	}

	@Column(name = "dni_usuarios", nullable = false)
	public int getDniUsuarios() {
		return this.dniUsuarios;
	}

	public void setDniUsuarios(int dniUsuarios) {
		this.dniUsuarios = dniUsuarios;
	}
	
	@Column(name = "idcarrera_carrera", nullable = false)
	public int getIdcarreraCarrera() {
		return this.idcarreraCarrera;
	}

	public void setIdcarreraCarrera(int idcarreraCarrera) {
		this.idcarreraCarrera = idcarreraCarrera;
	}

	@Column(name = "dorsal_participantes")
	public int getDorsalParticipantes() {
		return this.dorsalParticipantes;
	}

	public void setDorsalParticipantes(int dorsalParticipantes) {
		this.dorsalParticipantes = dorsalParticipantes;
	}

	@Column(name = "tiempo_participantes")
	public Integer getTiempoParticipantes() {
		return this.tiempoParticipantes;
	}

	public void setTiempoParticipantes(Integer tiempoParticipantes) {
		this.tiempoParticipantes = tiempoParticipantes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "version")
	public Date getTimestampParticipantes() {
		return this.timestampParticipantes;
	}

	public void setTimestampParticipantes(Date timestampParticipantes) {
		this.timestampParticipantes = timestampParticipantes;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParticipantesId))
			return false;
		ParticipantesId castOther = (ParticipantesId) other;

		return (this.getDniUsuarios() == castOther.getDniUsuarios())
				&& (this.getIdcarreraCarrera() == castOther.getIdcarreraCarrera())
				&& (this.getDorsalParticipantes() == castOther.getDorsalParticipantes())
				&& ((this.getTiempoParticipantes() == castOther.getTiempoParticipantes())
						|| (this.getTiempoParticipantes() != null && castOther.getTiempoParticipantes() != null
								&& this.getTiempoParticipantes().equals(castOther.getTiempoParticipantes())))
				&& ((this.getTimestampParticipantes() == castOther.getTimestampParticipantes())
						|| (this.getTimestampParticipantes() != null && castOther.getTimestampParticipantes() != null
								&& this.getTimestampParticipantes().equals(castOther.getTimestampParticipantes())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDniUsuarios();
		result = 37 * result + this.getIdcarreraCarrera();
		result = 37 * result + this.getDorsalParticipantes();
		result = 37 * result + (getTiempoParticipantes() == null ? 0 : this.getTiempoParticipantes().hashCode());
		result = 37 * result + (getTimestampParticipantes() == null ? 0 : this.getTimestampParticipantes().hashCode());
		return result;
	}

}
