package Modelo;
// Generated 18-abr-2018 14:18:14 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "bbdd_g2")
public class Usuarios implements java.io.Serializable {

	private int dniUsuarios;
	private String nombreUsuarios;
	private String apellidosUsuarios;
	private String emailUsuarios;
	private String passwordUsuarios;
	private int edadUsuarios;
	private String cpUsuarios;
	private String telefonoUsuarios;
	private Date timestampUsuarios;
	private Set<Participantes> participanteses = new HashSet<Participantes>(0);

	public Usuarios() {
	}

	public Usuarios(int dniUsuarios, String nombreUsuarios, String apellidosUsuarios, String emailUsuarios,
			String passwordUsuarios, int edadUsuarios, String cpUsuarios, String telefonoUsuarios) {
		this.dniUsuarios = dniUsuarios;
		this.nombreUsuarios = nombreUsuarios;
		this.apellidosUsuarios = apellidosUsuarios;
		this.emailUsuarios = emailUsuarios;
		this.passwordUsuarios = passwordUsuarios;
		this.edadUsuarios = edadUsuarios;
		this.cpUsuarios = cpUsuarios;
		this.telefonoUsuarios = telefonoUsuarios;
	}

	public Usuarios(int dniUsuarios, String nombreUsuarios, String apellidosUsuarios, String emailUsuarios,
			String passwordUsuarios, int edadUsuarios, String cpUsuarios, String telefonoUsuarios, Set<Participantes> participanteses) {
		this.dniUsuarios = dniUsuarios;
		this.nombreUsuarios = nombreUsuarios;
		this.apellidosUsuarios = apellidosUsuarios;
		this.emailUsuarios = emailUsuarios;
		this.passwordUsuarios = passwordUsuarios;
		this.edadUsuarios = edadUsuarios;
		this.cpUsuarios = cpUsuarios;
		this.telefonoUsuarios = telefonoUsuarios;
		this.participanteses = participanteses;
	}

	@Id

	@Column(name = "DNI_usuarios", unique = true, nullable = false)
	public int getDniUsuarios() {
		return this.dniUsuarios;
	}

	public void setDniUsuarios(int dniUsuarios) {
		this.dniUsuarios = dniUsuarios;
	}

	@Column(name = "nombre_usuarios", nullable = false, length = 45)
	public String getNombreUsuarios() {
		return this.nombreUsuarios;
	}

	public void setNombreUsuarios(String nombreUsuarios) {
		this.nombreUsuarios = nombreUsuarios;
	}

	@Column(name = "apellidos_usuarios", nullable = false, length = 70)
	public String getApellidosUsuarios() {
		return this.apellidosUsuarios;
	}

	public void setApellidosUsuarios(String apellidosUsuarios) {
		this.apellidosUsuarios = apellidosUsuarios;
	}

	@Column(name = "email_usuarios", nullable = false, length = 50)
	public String getEmailUsuarios() {
		return this.emailUsuarios;
	}

	public void setEmailUsuarios(String emailUsuarios) {
		this.emailUsuarios = emailUsuarios;
	}

	@Column(name = "password_usuarios", nullable = false, length = 45)
	public String getPasswordUsuarios() {
		return this.passwordUsuarios;
	}

	public void setPasswordUsuarios(String passwordUsuarios) {
		this.passwordUsuarios = passwordUsuarios;
	}

	@Column(name = "edad_usuarios", nullable = false)
	public int getEdadUsuarios() {
		return this.edadUsuarios;
	}

	public void setEdadUsuarios(int edadUsuarios) {
		this.edadUsuarios = edadUsuarios;
	}

	@Column(name = "cp_usuarios", nullable = false, length = 10)
	public String getCpUsuarios() {
		return this.cpUsuarios;
	}

	public void setCpUsuarios(String cpUsuarios) {
		this.cpUsuarios = cpUsuarios;
	}

	@Column(name = "telefono_usuarios", nullable = false, length = 15)
	public String getTelefonoUsuarios() {
		return this.telefonoUsuarios;
	}

	public void setTelefonoUsuarios(String telefonoUsuarios) {
		this.telefonoUsuarios = telefonoUsuarios;
	}

	@Version@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "version", nullable = false)
	public Date getTimestampUsuarios() {
		return this.timestampUsuarios;
	}

	public void setTimestampUsuarios(Date timestampUsuarios) {
		this.timestampUsuarios = timestampUsuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<Participantes> getParticipanteses() {
		return this.participanteses;
	}

	public void setParticipanteses(Set<Participantes> participanteses) {
		this.participanteses = participanteses;
	}

}
